/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ADark: typeof import('./src/components/ADark.vue')['default']
    ASearch: typeof import('./src/components/ASearch.vue')['default']
    ATab: typeof import('./src/components/ATab.vue')['default']
    Components: typeof import('./src/components/index.vue')['default']
  }
}
