/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AButton: typeof import('./src/components/AButton.vue')['default']
    AIconDialog: typeof import('./src/components/AIconDialog.vue')['default']
    AInput: typeof import('./src/components/AInput.vue')['default']
    ASiteBlock: typeof import('./src/components/ASiteBlock.vue')['default']
    Header: typeof import('./src/components/Header.vue')['default']
    Plum: typeof import('./src/components/Plum.vue')['default']
    Search: typeof import('./src/components/Search.vue')['default']
    Tab: typeof import('./src/components/Tab.vue')['default']
  }
}
