/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AButton: typeof import('./src/components/AButton.vue')['default']
    ADark: typeof import('./src/components/ADark.vue')['default']
    AIconDialog: typeof import('./src/components/AIconDialog.vue')['default']
    AInput: typeof import('./src/components/AInput.vue')['default']
    APlum: typeof import('./src/components/APlum.vue')['default']
    ASearch: typeof import('./src/components/ASearch.vue')['default']
    ASiteBlock: typeof import('./src/components/ASiteBlock.vue')['default']
    Tab: typeof import('./src/components/Tab.vue')['default']
  }
}
