// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AddIcon: typeof import('./src/components/icon/AddIcon.vue')['default']
    ArrowDownIcon: typeof import('./src/components/icon/ArrowDownIcon.vue')['default']
    CloseIcon: typeof import('./src/components/icon/CloseIcon.vue')['default']
    RightMemu: typeof import('./src/components/RightMemu/index.vue')['default']
    SearchIcon: typeof import('./src/components/icon/SearchIcon.vue')['default']
  }
}
