// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ArrowDownIcon: typeof import('./src/components/icon/ArrowDownIcon.vue')['default']
    CloseIcon: typeof import('./src/components/icon/CloseIcon.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchIcon: typeof import('./src/components/icon/SearchIcon.vue')['default']
    SearchInput: typeof import('./src/components/searchInput/index.vue')['default']
  }
}
