// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AddIcon: typeof import('./src/components/icon/AddIcon.vue')['default']
    AllDelIcon: typeof import('./src/components/icon/AllDelIcon.vue')['default']
    ArrowDownIcon: typeof import('./src/components/icon/ArrowDownIcon.vue')['default']
    BlueCheckIcon: typeof import('./src/components/icon/BlueCheckIcon.vue')['default']
    CheckIcon: typeof import('./src/components/icon/CheckIcon.vue')['default']
    CloseIcon: typeof import('./src/components/icon/CloseIcon.vue')['default']
    DelIcon: typeof import('./src/components/icon/DelIcon.vue')['default']
    Dialog: typeof import('./src/components/Dialog/index.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElColorPicker: typeof import('element-plus/es')['ElColorPicker']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElImage: typeof import('element-plus/es')['ElImage']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElSkeleton: typeof import('element-plus/es')['ElSkeleton']
    HandleIcon: typeof import('./src/components/icon/HandleIcon.vue')['default']
    ImageIcon: typeof import('./src/components/icon/ImageIcon.vue')['default']
    RightColDialog: typeof import('./src/components/RightColDialog/index.vue')['default']
    SearchIcon: typeof import('./src/components/icon/SearchIcon.vue')['default']
  }
  export interface ComponentCustomProperties {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
